### ISSUE TITLE
Set resource requirements for deployments

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/rdf-diff-store#63]
i.e:
```
        resources:
          requests:
            cpu: 5m
            memory: 5Gi
``` 
Adjust according to needs
